---
title: "Requal Roadmap"
author: "Radim Hladík"
email: "hladik@flu.cas.cz"
date: "2025-08-21"
date-modified: last-modified
version: "0.0.1.9008"
---

## Roadmap for the [Requal](https://requal.app) CAQDAS [project](github.com/RE-QDA/requal)

This is a high level overview. It is meant to offer a **general vision** of where the development of Requal should be heading. The roadmap doesn't involve bug fixes, minor features, and UI tweaks.

The roadmap is subject to continuous change. Timelines cannot be given, as much depends on external factors such as funding, project commitments, or simply coding challenges we encouter. 

## Milestone 2 - Advanced infrastructure (approx. v1.5)

Requal has in place the full data infrastructure for advanced QDA and integrates into the larger CAQDAS ecosystem.

- [ ] REFI-QDA import export
- [ ] RQDA import via UI
- [ ] Nested codes
- [ ] Attributes - backend
- [ ] Cases - backend
- [ ] Multiple files upload
- [ ] docx/odt text extraction

## Milestone 3 - Beyond basic (approx. v2.0)

Requal goes beyond the basic "code and retrieve" functionality.

- [ ] Attributes - frontend
- [ ] Cases - frontend
  - [ ] csv import for documents?
- [ ] External sources - PDF
- [ ] Programatic database updates
- [ ] Document organization
- [ ] Document editing

## Milestone 4 - Better analytics (approx. v2.5) 

Requal leverages the infrastructure of cases and attributes for boosting its analytical capabilities.

- [ ] Import surveys
- [ ] Visualizations and reports
- [ ] Quantitative content analysis
- [ ] Enable attributes and cases in retrieval
- [ ] Tags management tab

## Milestone 5 - Collaboration (approx. v3.0) 

Requal graduates from enabling collaboration to encouraging collaboration.

- [ ] Docker image for server version
- [ ] Admin page
- [ ] Authentication merged into Postgresql
- [ ] Revised documentation
- [ ] Revised permissions
- [ ] Full project back-up

## Milestone 6 - Expanded scope(approx. v4.0) 

Requal enlarges the scope of the data inputs and outputs.

- [ ] Multimedia sources 
- [ ] Mixed-methods support via R-exported functions

## Subprojects

::: {.callout-note}
Requal subprojects support its CAQDAS mission, but can branch in and out at various stages. Subprojects can be highly complex, but they generally do not affect the core development.
:::

- [ ] Anonymization tools (requires min. v1.5)
- [ ] Structured coding - basic TEI compatibility
- [ ] AI-assistant
- [ ] Standalone Electron installers
  - [X] Mac
  - [ ] Windows
  - [ ] Linux

## Major features

A list of major features that should appear in Requal at some point. Mostly a stock of ideas with varied levels of priority.

- [ ] Mutually linked memos
- [ ] Memos attached to
  - [X] segments
  - [ ] codings
  - [ ] codes
  - [ ] documents
  - [ ] cases
  - [ ] attributes
- [ ] Autocode (deterministic)
  - [ ] transcript level
  - [ ] database level?
- [ ] RTL support
  - [ ] Annotation
  - [ ] Retrieval
  - [ ] Other UI sections?
- [ ] Double-click editing
  - [ ] Codebook
- [ ] Code splitting
- [ ] Turbo coding
  - [ ] Turbo uncoding?
- [ ] In Vivo coding (sort of implemented via QuickTag)
  - [ ] Codings backlight
- [ ] Code editing from Annotation tab
- [ ] Transcript editing
  - [ ] Raw text
  - [ ] Coded text